### ISSUE TITLE
4.0 ?

### ISSUE THREAD

**Issue by nascentt** [dinosaurwithakatana/applist#1]
Firstly, thank so so much for open sourcing this app.  I've used it for many years it's incredibly handy to Import and Export all installed apps.

When I couldn't find the app in the google play store anymore, I hunted and was thrilled to find it open sourced here.

Strangley, however, this release seems to be at 3.1 but the version I had on the Google Play Store was 4.0

are there commits missing from this repo?

It'd be great to get this updated, it's such as well designed app.

**Comment by burntcookie90** [comment]
Wow, this is a throwback of a repo for me! It seems I may have built 4.0 off of the `develop` branch here https://github.com/dinosaurwithakatana/applist/tree/develop but never merged that back into `master` once released. Unfortunately, as you may notice this app/repo has been unmaintained for _a decade now_ and I dont think I'll be really making any time to update it to modern build standards, nor do I actively maintain any deployed play store applications anymore. I think the best course of action would be to fork and get it working on your own for sideloading.
